const LANDING_EASE = [0.22, 1, 0.36, 1] as const;
const NAME_DELAY = 0.05;
const CHAR_STAGGER = 0.04;
const CHAR_DURATION = 0.62;
const NAME_CHARACTER_COUNT = "SungjoonLee".length;
const BALL_DELAY = NAME_DELAY + (NAME_CHARACTER_COUNT - 1) * CHAR_STAGGER + CHAR_DURATION * 0.45;
const LANDING_REVEAL_DELAY = BALL_DELAY + 0.45;

export { BALL_DELAY, CHAR_DURATION, CHAR_STAGGER, LANDING_EASE, LANDING_REVEAL_DELAY, NAME_DELAY };
